apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wg-vpn

resources:
  - ../prod

patches:
  - target:
      kind: Deployment
      name: entry
    path: patch-entry-csi.yaml
  - target:
      kind: DaemonSet
      name: core
    path: patch-core-csi.yaml
